### ISSUE TITLE
control placement

### ISSUE THREAD

**Issue by vtolstov** [serialx/hashring#11]
Hi, does it possible to control placement (near, far) in case of using this package?
For example i have rack with servers and ring contains 40 nodes and i have 3 replica count, how can i specify that i need to place data on far servers?
Or another use-case - i have 3 racks and replica count 2, how can i place data on rack that far from another?

**Comment by serialx** [comment]
I’m not quite sure if this library is capable of rack-aware placement. Have a look at this: https://github.com/Netflix/dynomite/wiki/Replication
