### ISSUE TITLE
❕Misusing crypto/md5

### ISSUE THREAD

**Issue by liuchang1437** [serialx/hashring#17]
In the latest commit which “Allow passing a hash.Hash at creation time”, it allows to use custom hashers to calculate the hash value, not only `crypto/md5.Sum()`. 

**However, the code doesn't run as it should be when using the default hasher `md5.New()`.**

## Things are wrong
If you run following code listed at `README.md`, you would find that only two servers are inserted to the ring, when you print some info of the ring.
```go
serversInRing := []string{"192.168.0.246:11212",
                          "192.168.0.247:11212",
                          "192.168.0.248:11212",
                          "192.168.0.249:11212",
                          "192.168.0.250:11212",
                          "192.168.0.251:11212",
                          "192.168.0.252:11212"}

replicaCount := 3
ring := hashring.New(serversInRing)
server, _ := ring.GetNodes("my_key", replicaCount)
```

There is an open [issue](https://github.com/serialx/hashring/issues/16) reporting similar problems.

## Inspect the code
In earlier version, it uses `md5.Sum([]byte(key))` to calculate hash values. 
```go
// crypto/md5
func Sum(data []byte) [Size]byte {
	var d digest
	d.Reset()
	d.Write(data)
	return d.checkSum()
}
```
For now, it creates a new digest when you use a default hasher. And it calculates hash values by calling `digest.Sum(in []byte)`. Here comes the problem. They are not the same function at all!
```go
// crypto/md5
func (d *digest) Sum(in []byte) []byte {
	// Make a copy of d so that caller can keep writing and summing.
	d0 := *d
	hash := d0.checkSum()
	return append(in, hash[:]...)
}
```
**`digest.Sum()` simply returns what it receives following the check sum of the same old data.** This is not what we expect!

## Try to solve it
Maybe the correct way:
```
func (h *HashRing) hashDigest(key string) []byte {
	h.hasher.Write([]byte(key))
	return h.hasher.Sum(nil)
}
```
I'm not familiar with hash things, and I'm not sure whether it's ok for other hashers. But at least, it works for the default hasher.

**Comment by codepiano** [comment]
you are right, we met the same problem too.

**Comment by serialx** [comment]
Code is merged!
