### ISSUE TITLE
i wonder about.

### ISSUE THREAD

**Issue by cssivision** [serialx/hashring#9]
could you tell me the reason?

1, why use `40` there?
```go
factor := math.Floor(float64(40*len(h.nodes)*weight) / float64(totalWeight))
```

2,  why use `3` there?
```go
for i := 0; i < 3; i++ {
	key := hashVal(bKey[i*4 : i*4+4])
        h.ring[key] = node
	h.sortedKeys = append(h.sortedKeys, key)
}
```
thanks

**Comment by serialx** [comment]
This is a port from libketama with portability in mind. You should ask the author of libketama for these constants.

See: https://github.com/RJ/ketama/blob/master/libketama/ketama.c#L438

**Comment by JordanP** [comment]
This is the number of virtualNode a.k.a vnode. This is an important parameter. Basically, each actual server is seen as 160 virtual servers. In the hope of achieving better load distribution. In other implementations, this constant is called `ketama_points` [1] or `KETAMA_NVNODE`.

IMO this should be documented in the readme.md of this project for completeness. 

[1] http://search.cpan.org/~raz/Cache-Memcached-Fast-0.25/lib/Cache/Memcached/Fast.pm
[2] https://gitlab.com/nginx-modules/ngx_http_upstream_ketama_chash/blob/master/ngx_http_upstream_ketama_chash_module.c#L37

**Comment by pikeszfish** [comment]
@serialx 
```
for i := 0; i < 3; i++ {
	key := hashVal(bKey[i*4 : i*4+4])
        h.ring[key] = node
	h.sortedKeys = append(h.sortedKeys, key)
}
```
I think it's only loop for 3 times here. Is that right?

**Comment by pikeszfish** [comment]
Fine. I got it. 
@cssivision @serialx 
https://github.com/3rd-Eden/node-hashring/blob/master/index.js#L57-L72
